### ISSUE TITLE
file permissions settings.php fail on OSX 10.10

### ISSUE THREAD

**Issue by zikphil** [FloeDesignTechnologies/ansible-drupal-settings#3]
Hi,

Following a vagrant up, i am unable to to run this role because it throws the following error:

```
TASK: [villette.drupal-settings | Make sure the settings.php files are writable] ***
failed: [default] => (item={'key': 'defa...

msg: Error while touching existing target: [Errno 13] Permission denied: '/var/www/sites/default/settings.php'

FATAL: all hosts have already failed -- aborting
```

If i go in ssh and change the permission to 666, then provision, it works fine.

**Comment by villette** [comment]
[This pull request](https://github.com/FloeDesignTechnologies/ansible-drupal-settings/pull/4) fixes this error, I've just merged it. Thank you to have brought this up.
